### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by fordp2002** [blinky101/examples_lpc43xx#1]
Hi, I think this repository may be really useful to me but without a readme I am not sure!

It would be great to have a readme detailing the tools used to build including versions.

If I find it useful and you open the wiki up to editing then I will add some content there.

Cheers.

**Comment by ijager** [comment]
Hi @fordp2002,

Good point. We'll try to make some time to add a top level Readme. In the meantime, the subdirectories in this repository do have Readme files. And for each project the `CMakeLists.txt` file lists all required versions.

You could also take a look at [this Getting Started Guide](https://blinky101.github.io/blinky_lpc43xx/getting_started) and [this tutorial](https://blinky101.github.io/blinky_lpc43xx/tutorial_part3) for more information about the CPM package manager and the required tools.

Let me know if you miss any information.

**Comment by ijager** [comment]
We've added a readme and opened up the wiki for if you like to add some content.

**Comment by fordp2002** [comment]
Great, many thanks!
